supabase/auth-helpers

src/nextjs/README.md, src/nextjs/handlers/callback.ts, src/nextjs/handlers/logout.ts
Closes #40 
Closes supabase/supabase#347
Adds a similar cookie persistence mechanism for `provider_token` to those used for `access_token` and `refresh_token` in [src/nextjs/handlers/callback.ts](https://github.com/supabase-community/supabase-auth-helpers/blob/e188cb903cd532aa438729fda4269bed53b3fff5/src/nextjs/handlers/callback.ts)
Additionally, this cookie is cleared on SIGNED_OUT in both [src/nextjs/handlers/callback.ts](https://github.com/supabase-community/supabase-auth-helpers/blob/e188cb903cd532aa438729fda4269bed53b3fff5/src/nextjs/handlers/callback.ts) and [src/nextjs/handlers/logout.ts](https://github.com/supabase-community/supabase-auth-helpers/blob/e188cb903cd532aa438729fda4269bed53b3fff5/src/nextjs/handlers/logout.ts)
Finally, a usage example was added to …
=> feat: Persist `provider_token` to HTTPOnly cookie on SIGNED_IN

CHANGELOG.md, package-lock.json, package.json, src/nextjs/middleware/withMiddlewareAuth.ts, src/package-lock.json, src/package.json, src/shared/utils/jwt.ts
- [#102](https://github.com/supabase-community/supabase-auth-helpers/pull/102): fix: use jose to decode JWT. Fixes #97; Fixes #98; Fixes #99
=> fix: use jose to decode JWT

packages/sveltekit/src/utils/supabaseServerClient.ts, packages/sveltekit/src/utils/withApiAuth.ts
When a request is passed in to `supabaseServerClient` it was looking at the header for the access token. This pulls the access token off of the cookie header.
When using `withApiAuth`, the returned type was hardcoded to `{}`. This allows the proper types to be inferred from the function so they may be used downstream. See this [TS Playground](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAWxgZzTMBzAKgTwAcBTACmDAC5FSBKAXgD5EBvAX1pYChFfEAnYlBD8kFOgG4ubLl1CRYCRFmDF+ggCYESAHlyNyVGg2a5OPPoOGjE42lJlzw0eEijE0UOqwu8rIpBZgODhqAHIARgAmAGYwgBpEACMAQ35wgBYAVgA2MJlHCARPAQ9CYuJEehR0TBxtMndPWlkisBLBNHL24iiq5TBVdWItIkaPKFogA) for an example.
=> SvelteKit: Fix supabaseServerClient with request and withApiAuth return type

packages/nextjs/src/handlers/auth.ts, packages/nextjs/src/handlers/callback.ts
Fixed typo `handelCallback` to `handleCallback`
=> Fix typo in nextjs auth callback handler

packages/sveltekit/README.md
Fixes link to example .env file in Sveltekit README
Fixes #210
=> Fixes link to Sveltekit .env.example file

packages/nextjs/README.md
This is a minor typo. It doesn't deserve any context.
=> docs(nextjs): typo in readme

.changeset/dirty-swans-warn.md, packages/nextjs/src/handlers/logout.ts
* Allows one to pass the domain and path in handleLogout to clear the cookies. This is particularly useful if you intend to clear all cookies related to a base domain.
* Note: This is just a patch for the version in `main` - we don't need to handle this in `next` since the logout route is removed
=> fix: pass domain & path in logout

packages/sveltekit/src/server/handlers/callback.ts
Fixes #216 
Bug fix
`/api/auth/callback` catches non-POST methods
non-POST methods are ignored
We don´t need to check for the method, sveltekit emits a 405 status on its own.
=> ignore non-POST requests

.changeset/many-weeks-rush.md, examples/nextjs/db_types.ts, examples/nextjs/pages/_app.tsx, examples/nextjs/pages/index.tsx, packages/nextjs/MIGRATION_GUIDE.md, packages/nextjs/README.md, packages/react/src/components/SessionContext.tsx
Fixes #273 
You can pass types that were [generated with the Supabase CLI](https://supabase.com/docs/reference/javascript/next/typescript-support#generating-types) to the Supabase Client to get enhanced type safety and auto completion:
```js
// Creating a new supabase client object:
import { Database } from '../db_types';
const [supabaseClient] = useState(() =>
createBrowserSupabaseClient<Database>()
);
```
```js
// Retrieving a supabase client object from the SessionContext:
import { useSupabaseClient } from '@supabase/auth-helpers-react';
import { Database } from '../db_types';
const supabaseClient = useSupabaseClient<Database>();
```
=> fix: type useSupabaseClient

.changeset/light-eggs-relax.md, .changeset/quick-pugs-think.md, .changeset/quiet-toys-guess.md, .changeset/tender-flowers-search.md, examples/sveltekit-email-password/package.json, examples/sveltekit-magic-link/package.json, examples/sveltekit/package.json, packages/nextjs/package.json, packages/react/package.json, packages/shared/package.json, packages/sveltekit/package.json, packages/sveltekit/src/utils/getServerSession.ts, pnpm-lock.yaml
Update to supabase-js 2.0.4
We are currently missusing `setSession(session)` to refresh the session in sveltekit.
Use the new `refreshSession()` method
=> update supabase js

.changeset/sixty-dolls-tickle.md, packages/sveltekit/src/utils/supabase-load.ts
fixes #343
Bug fix
The supabase instance created in shared load functions on the server auto refreshes the token
no auto refresh on the server side
=> sveltekit ssr disable auto token refresh

.changeset/sour-carrots-own.md, examples/nextjs/.gitignore, examples/nextjs/pages/_app.tsx, examples/nextjs/pages/index.tsx, examples/sveltekit/src/routes/+page.svelte, packages/remix/src/constants.ts, packages/shared/src/supabase-browser.ts, packages/shared/src/supabase-server.ts, packages/shared/src/utils/cookies.ts
Strip down the cookie to only store the tokens and construct the session by decoding the `access_token`.
In a next step we should look into splitting the cookie up into chunks since the `access_token` itself could exceed 4kb.
=> chore: reduce cookie size

.changeset/fifty-dryers-look.md, packages/nextjs/src/utils/withPageAuth.ts
Fix a bug with `withPageAuth` when a session is `null` and `authRequired` is set to false.
Bug fix
I reported this bug on discord: https://discord.com/channels/839993398554656828/1036308519755984986/1036308519755984986
With a code similar to this:
```ts
export const getServerSideProps = withPageAuth<Database>({
authRequired: false,
async getServerSideProps(ctx, supabase) {
try {
const { id } = ctx.query
const response = await supabase
.from('Videos')
.select(`
title,
description,
likes,
dislikes,
views,
created_at,
VideoLikes (
type
),
Profiles (
username,
profile_picture_url
),
Servers (
id,
name
)
`)
.eq('id', id)
.limit(1)
.single()
return {
props: {
video: response.data,
userRating: response.data?.VideoLikes && response.data.VideoLikes[0] ? response.data.VideoLikes[0]['type'] : 0
}
} …
```
=> Fix a bug with withPageAuth when a session is null and authRequired is set to false

.changeset/tasty-schools-kneel.md, packages/nextjs/src/middleware/withMiddlewareAuth.ts, packages/nextjs/src/utils/withApiAuth.ts
What kind of change does this PR introduce?
Updates the code to read headers from the request instead of the response. Fixes #358
What is the current behavior?
The headers are read from the response
What is the new behavior?
The headers are read from the request
=> adding fix for host missing

.changeset/green-cows-play.md, packages/shared/src/utils/cookies.ts
Fixes [the unicode problem](https://developer.mozilla.org/en-US/docs/Glossary/Base64#the_unicode_problem) by converting the string to percent-encoding before being decoded
Note: the escape function is obsolete, which is why i went with this fix
The atob function cannot decode chars outside the latin1 range
characters outside the latin1 range can be decoded
fixes #359
=> 359-session-data-comes-back-encoded

examples/nextjs-server-components/app/layout.tsx, examples/nextjs-server-components/app/optional-session/page.tsx, examples/nextjs-server-components/app/realtime/new-post.tsx, examples/nextjs-server-components/app/realtime/page.tsx, examples/nextjs-server-components/app/realtime/realtime-posts.tsx, examples/nextjs-server-components/app/required-session/page.tsx, examples/nextjs-server-components/components/login.tsx, examples/nextjs-server-components/components/supabase-listener.tsx, examples/nextjs-server-components/components/supabase-provider.tsx, examples/nextjs-server-components/db_types.ts, examples/nextjs-server-components/utils/supabase-browser.ts, examples/nextjs-server-components/utils/supabase-server.ts, examples/nextjs-server-components/utils/supabase.ts
Simplifies the Next.js 13 Server Components example
- instantiating server client is cleaner
- more clear separation of client and server
- single supbase instance for client-side (shared through context)
- fix useEffect dependencies
=> Chore: Update next.js server components example

.changeset/olive-jeans-juggle.md, tsconfig.json
This is a bug fix, there was a reference to an old svelte path that doesn't exist and that was causing some TypeScript errors.
=> removed the old svelte reference

packages/sveltekit/README.md
Clarifies confusion about how DatabaseDefinitions was created using Supabase CLI. This clears some potential confusion and clarifies #289, where the user should have the import point to their types file.
=> Specify DatabaseDefinitions origins for Sveltekit (Get types working)

.changeset/dull-terms-smell.md, packages/nextjs/src/index.ts, packages/remix/src/utils/createSupabaseClient.ts, packages/shared/src/supabase-browser.ts, packages/shared/src/supabase-server.ts, packages/shared/src/types.ts, packages/sveltekit/src/createClient.ts, packages/sveltekit/src/index.ts
Allow passing of client options for nextjs and remix https://github.com/supabase/auth-helpers/issues/420
Client options can´t be passed.
client options can be passed:
```ts
import { createBrowserSupabaseClient } from '@supabase/auth-helpers-nextjs';
const supabaseClient = createBrowserSupabaseClient({
options: {
...
}
});
```
The auth key is omitted as it is set internally by the helper
=> Allow passing client options

.changeset/real-spiders-drive.md, packages/nextjs/src/index.ts
Allow overwriting of client URL and key in Next.js helpers
fixes #384
Values must be set from env variables
Values can be set in create*SupabaseClient functions
```ts
createBrowserSupabaseClient({
supabaseUrl: 'supabase-url',
supabaseKey: 'supabase-anon-key',
})
```
Defaults to the env variables so this isn´t a breaking change
Added options for `createServerComponentSupabaseClient` as that was missed in #428
=> feat: next allow overwriting url and key

packages/sveltekit/src/supabaseLoadClient.ts
TS types bug fix with new SvelteKit client.
Returned client wasn't correctly narrowing `SchemaName` in `SupabaseClient`.
Returned type is correctly narrowed with generic parameters
The second change forces the cached client to return with the same type.
=> [SvelteKit] Correctly type returned and cached client with generic param

.changeset/fresh-scissors-beg.md, packages/shared/src/utils/cookies.ts
Bug fix
When calling `stringifySupabaseSession` to build the session string, factors are not added to the list, this makes `getAuthenticatorAssuranceLevel` return the wrong `aal` data because this condition:
```typescript
//  inside getAuthenticatorAssuranceLevel definition
const verifiedFactors =
session.user.factors?.filter((factor: Factor) => factor.status === 'verified') ?? []
```
Factors are added to the session
=> Adds MFA factors into session

.changeset/mean-gifts-hunt.md
I was excited to see the sveltekit overhaul merged into main but noticed there was no changeset file to trigger a new release. This is a simple change to resolve that. I noticed the merge includes small changes to other packages but opted to not include them keep the release specific to svelte. Thanks for the work on this!
=> sveltekit changeset

.changeset/selfish-pears-applaud.md, packages/nextjs/src/index.ts
feature
You need to create a Server Component Supabase Client in Route Handler functions
Export a new `createRouteHandlerSupabaseClient` function for use in Route Handler functions
=> Feature: Add route handler package for app directory

examples/nextjs-server-components/middleware.tsx
This project runs on Next 13 so ts ignore is no longer needed.
Docs update
=> Next-server-components: Update middlware.tsx

packages/sveltekit/README.md
Replace `invalid` with [sveltekit actions `fail` method](https://kit.svelte.dev/docs/modules#sveltejs-kit-fail).
Docs update
=> Docs: use sveltekit action fail method

packages/react/src/components/SessionContext.tsx
Bug fix for issue #426
Previously, the mount variable was always true.
=> Fix #426: set unmount variable when unmounting

examples/remix/app/routes/__supabase.tsx
In some cases, an auth state change was causing an infinite loop of useEffect. This checks the state of the fetcher before calling submit to make sure it isn't already being submitted.
Bug fix in example
I didn't see this when running the simple example app, but ran into it with my own app which had no differences in the __supabase.tsx file. When clicking logout or completing login, the browser would freeze because the render was doing an infinite loop of the useEffect.
[Remix #4386](https://github.com/remix-run/remix/pull/4386)
Infinite loop doesn't occur.
=> Remix example: Check fetcher state to avoid infinite loop

.changeset/brave-lizards-thank.md, packages/nextjs/src/middlewareClient.ts
Bug fix
When using the `createMiddlewareSupabaseClient` inside a middleware the storage driver would throw an error due to the cookie being saved twice.
There is no longer an error and cookie is only saved once.
=> Fix Failed to parse cookie string in middleware

.changeset/six-eggs-search.md, packages/nextjs/src/clientComponentClient.ts, packages/nextjs/src/deprecated.ts, packages/nextjs/src/index.ts, packages/nextjs/src/middlewareClient.ts, packages/nextjs/src/pagesBrowserClient.ts, packages/nextjs/src/pagesServerClient.ts, packages/nextjs/src/routeHandlerClient.ts, packages/nextjs/src/serverActionClient.ts, packages/nextjs/src/serverComponentClient.ts
Chore
1. createClient functions do not follow a clear convention
2. pages directory createClient functions are the default - no longer the recommended path
The App Router createClient functions follow a contextual convention as to where they are being used:
- createClientComponentClient
- createServerComponentClient
- createMiddlewareClient
- createRouteHandlerClient
- createServerActionClient
Pages directory createClient functions now contain `pages` in their name
- createPagesBrowserClient
- createPagesServerClient
---
Have also removed the `Supabase` part of each export, as this feels unnecessary.
We cannot consolidate all server-side functions into a single createServerClient function, as Server Components will not be able to `set` cookies, therefore, will always need to use …
=> Chore: Implement naming convention for createClient functions

.changeset/pre.json, .changeset/silly-laws-give.md, packages/nextjs/src/clientComponentClient.ts
chore
Every time you call the `createClientComponentClient` function it creates a new Supabase instance. It is important that a single instance of Supabase is shared across all Client Components. This is implementation information about Supabase that shouldn't need to be understood by someone new to Supabase.
No matter how many times you call the createClientComponentClient function, you only ever create a single instance. This means our documentation can be simplified, and people can get started with Supabase more quickly.
=> Chore: Implement singleton pattern for createClientComponentClient function

.changeset/many-avocados-fetch.md, .changeset/pre.json, packages/nextjs/src/middlewareClient.ts
Bug fix
Middleware only appends a `set-cookie` header, which is not available in the Server Component on the first render.
Middleware also sets a `cookie` header, which is available immediately in the Server Component
=> Fix: Set response cookie

.changeset/pre.json, .changeset/strange-mugs-know.md, packages/nextjs/package.json, packages/nextjs/src/index.ts, packages/nextjs/src/routeHandlerClient.ts, pnpm-lock.yaml
Chore
We use a custom type for WritableCookies as Next.js type had not been updated with the new `.set` method.
Use Next.js 13.4.3 type for `ReadonlyRequestCookies`, which now contains the `.set` method.
=> Chore: Update Next.js and remove custom type for WritableCookies

.changeset/curly-stingrays-peel.md, packages/nextjs/src/clientComponentClient.ts, packages/nextjs/src/deprecated.ts, packages/nextjs/src/middlewareClient.ts, packages/nextjs/src/pagesServerClient.ts, packages/nextjs/src/routeHandlerClient.ts, packages/nextjs/src/serverComponentClient.ts
Bug fix
Return types were not being correctly provided from createClient functions
All createClient functions now return `SupabaseClient<Database, SchemaName, Schema>`
Also added deprecated functions for previous App Router createClient functions so we don't break existing apps! 🧠
=> Fix: Typedefs for clientClient functions

.changeset/unlucky-planes-think.md, packages/nextjs/src/clientComponentClient.ts
Bug fix
Client Components could not create multiple Supabase clients.
A new config option for `isSingleton` is exposed on the `createClientComponentClient` function, to allow for multiple Supabase clients.
https://github.com/supabase/auth-helpers/issues/563
=> Chore: Extend config options to allow for multiple Supabase clients

.changeset/heavy-elephants-stare.md, packages/shared/src/utils/helpers.ts
This fixes a bug when deploying to edge functions on Netlify using SvelteKit. This might also fix some other future bugs.
Since Netlify Edge Functions run on Deno, `window` is defined. So using `typeof window !== 'undefined'` will actually result true.
This patch makes the `isBrowser` helper function double check if the current environment is a browser.
Related: https://github.com/sveltejs/kit/issues/9810
=> fix: isBrowser helper function on deno

examples/sveltekit/README.md
Docs update.
The  command to run the Sveltekit example is incorrect, resulting in the behavior below:
<details>
<summary>Before</summary>
</details>
The command to run the Sveltekit example has been corrected, so the app runs successfully:  
<details>
<summary>After</summary>
</details>
=> Fix command to run Sveltekit example

.changeset/lazy-colts-add.md, packages/nextjs/src/routeHandlerClient.ts
router client was not respecting the cookieOptions this fixes that. Allowing auth to work across all subdomains in Nextjs applications.
Fixes: https://github.com/orgs/supabase/discussions/5742
Fixes: https://github.com/orgs/supabase/discussions/3198
=> Update routeHandlerClient.ts add cookieOptions

.changeset/flat-seas-attack.md, packages/react/src/components/SessionContext.tsx
Resolves #586
This is a bug/logic fix for how `initialSession` is handled in the `SessionContextProvider`.
At present, `initialSession` is passed into `useState`, which means that it is discarded after the first render. The issue here is that this is often on a login page where it will likely be `undefined`, meaning any session subsequently created on the server side is discarded.
I’ve just added a `useEffect` that sets the session state if `initialSession` is available and `session` is not.
=> Handle initialSession changes in context provider

.changeset/shy-cats-warn.md, packages/nextjs/src/deprecated.ts, packages/nextjs/src/routeHandlerClient.ts, packages/nextjs/src/serverComponentClient.ts, packages/react/src/components/SessionContext.tsx
Types
Import type from Next.js `dist` folder for `cookies()` and `headers()` functions
The type is inferred from the return type of the functions
=> Fix: types for next cookies and headers functions

.changeset/healthy-clocks-approve.md, packages/sveltekit/package.json
Opened because I accidentally closed #600
- Expands bundler/TS support, corrects https://publint.dev/ warnings
For @supabase/auth-helpers-sveltekit:
```This entrypoint has types at ./dist/index.d.ts but it is not exported from pkg.exports. Consider adding it to pkg.exports["."].types to be compatible with TypeScript's "moduleResolution": "bundler" compiler option.```
- Warnings removed by adding `exports["."]["types"]` and `exports["."]["import"]` fields
=> feat(sveltekit): Fix export fields in package.json

.changeset/few-carrots-mate.md, packages/nextjs/src/middlewareClient.ts, packages/nextjs/src/pagesServerClient.ts, packages/shared/src/cookieAuthStorageAdapter.ts, packages/shared/src/types.ts, packages/shared/src/utils/constants.ts
Fixing a bug where we allowed the developer to set the cookie max-age, but we are using cookies only as a storage mechanism for the JWT which already has an expiry time. Closes #635 
This can currently be set by the developer
This can no longer be set by the developer
=> Remove max-age option from cookieOptions

.changeset/great-beds-pull.md, packages/ssr/src/createBrowserClient.ts, packages/ssr/src/createServerClient.ts, packages/ssr/src/types.ts
Chore
Cookie functions are mandatory when creating s Server client
Cookie functions are optional when creating s Server client
Next.js Server Components cannot set or remove cookies. It doesn't make sense to declare these empty functions to be able to use a Supabase client in a Server Component
=> Chore: make cookie functions optional in server client

.changeset/honest-ways-build.md, packages/ssr/src/createBrowserClient.ts, packages/ssr/src/createServerClient.ts
Bug fix
We do not await `get` method
We await `get` method
=> Fix: await get method

.changeset/empty-carrots-learn.md, packages/nextjs/src/routeHandlerClient.ts
Adds `this.cookieOptions` when calling `deleteCookie`
If cookie is set by a specific domain it cannot be deleted since `deleteCookie` only specifiy `maxAge` as option and not others like `domain`.
=> fix: include cookieOptions for deleteCookie

.changeset/hot-stingrays-laugh.md, packages/nextjs/src/pagesServerClient.ts
Bug fix of trying to read the header or cookie from an empty or undefined response
The previous behavior introduced with the latest version of nextjs (14.0.1) caused a lot of console spam in development and erroring out with 500 codes in every single request on production.
This fixes the console spam and the production erroring.
This simple fix doesnt change much, and the behavior of the auth helpers remains the same.
=> fix: header reading trying to access undefined res on nextjs

.changeset/olive-plums-flash.md, packages/ssr/src/createBrowserClient.ts, packages/ssr/src/createServerClient.ts, packages/ssr/src/utils/chunker.ts
Fix
Some OAuth signin methods are failing due to size of cookie being too big
Implements cookie chunking to ensure size of each cookie is not too big
=> Fix: add cookie chunking as default to ssr package

.changeset/violet-windows-invite.md, packages/ssr/src/utils/chunker.ts, packages/ssr/src/utils/constants.ts
Cookie size is still too big and this PR aims to reduce that
The first chunk is too big so the browser ignores it and doesn't save it.
All chunks should be within the browser size limit
Addresses #668 #661
=> Reduce cookie chunk size

.changeset/witty-months-tap.md, packages/ssr/src/utils/constants.ts
Bug fix
The browser cookie is not set to httpOnly: false which breaks the ssr package behaviour
The browser cookie is set to httpOnly: false
Fixes #681
=> Set cookie default to httpOnly: false

.changeset/empty-oranges-hug.md, packages/sveltekit/package.json, packages/sveltekit/src/serverStorageAdapter.ts, pnpm-lock.yaml
Versions upgrade, fixes #706
Currently unable to persist cookies without specifying a `path` per SvelteKit 2 docs:
Sets path to '/' by default, making it compatible with SvelteKit 1 and 2.
=> add support for sveltekit 2

CODEOWNERS
* Adds the auth team as the codeowners for the auth helpers
=> chore: add auth team as codeowners

examples/sveltekit/package.json, package.json, packages/sveltekit/package.json, pnpm-lock.yaml
We upgrade Vite to 5.0 to resolve some of the dependabot errors here is [one example](https://github.com/supabase/auth-helpers/security/dependabot/67)
We also bump Sveltekit to 1.30.3 as earlier versions depend on Vite V4
=> feat: upgrade svelte version

packages/ssr/src/utils/chunker.ts, packages/ssr/tests/chunker.spec.ts
Bug fix
The length of cookies with URI escaped characters can exceed the valid cookie length of 4096, causing parts of the split cookies to be rejected by the browser.
Chunked cookies after URI encoding now fit within the chunk size specified.
The reason for this issue occurring is that we are chunking base on lengths before escaping. While we have some buffer in the `MAX_CHUNK_SIZE` for longer unicode characters, this does not always work.
For example `﷽` has a length in javascript of `1` as well as match `/(.{1})/g.exec("﷽") ` to be `$1 = ﷽`, but it will escape to `%EF%B7%BD` which is 9 characters long.
The current approach of chunking with a buffer for some unicode characters will never be "correct" unless we implement a buffer that accounts for every character being a maximum size …
=> fix(chunker): Fix chunk length calculation for unicode characters

package-lock.json, packages/nextjs/src/serverComponentClient.ts, packages/remix/src/createSupabaseClient.ts, packages/ssr/src/createBrowserClient.ts, packages/ssr/src/createServerClient.ts, packages/sveltekit/src/serverStorageAdapter.ts
This property will be picked up by [auth-js (formerly known as gotrue-js)](https://github.com/supabase/gotrue-js) to warn or adjust behavior given that the storage medium (in this case cookies) cannot be trusted.
=> feat: add `isServer` property to server-side storage adapters

packages/nextjs/package.json, packages/react/package.json, packages/remix/package.json, packages/shared/package.json, packages/sveltekit/package.json, pnpm-lock.yaml
Fix. right now types definitions are not working when using ssr library added https://github.com/supabase/storage-js/pull/190
When in the console when we log the data is -> 
I'm not having type completation
=> fix: bump supabase-js to match lastest types.

.changeset/proud-coins-help.md, packages/ssr/src/createBrowserClient.ts
* Address [the comment](https://github.com/supabase/auth-helpers/issues/717#issuecomment-1962251408) raised in #717 
* `createBrowserClient` in the ssr package also doesn't seem to respect the custom cookie name used
=> fix: allow setting custom cookie name in createBrowserClient

.changeset/bright-ravens-confess.md, packages/ssr/src/createBrowserClient.ts, packages/ssr/src/createServerClient.ts, packages/ssr/src/utils/chunker.ts
Fixes/improves some edge cases in the cookie chunker for `ssr`:
1. `deleteChunks` now attempts to delete both the key and potential leftover chunks, instead of deleting the first thing it notices. This should decrease the total size of cookies by removing orphaned chunks, and also is a bit safer in situations where leftover chunks are mistaken as the continuation of other chunks.
2. Avoid using parallel cookie setting in `setItem`, and instead do it serially.
3. `setItem` first clears all chunks before setting the new ones.
=> fix: small improvements/fixes to cookie chunker in ssr

README.md
Docs update
Clicking the current link to the migration docs leads to https://github.com/supabase/auth-helpers/blob/main/docs/guides/auth/server-side/migrating-to-ssr-from-auth-helpers which is 404 page not found. 
The intended functionality is taking them to https://supabase.com/docs/guides/auth/server-side/migrating-to-ssr-from-auth-helpers?queryGroups=framework&framework=nextjs
Links to the correct URL - https://supabase.com/docs/guides/auth/server-side/migrating-to-ssr-from-auth-helpers
=> fix: update broken link to the migration doc
