src/nextjs/handlers/auth.ts, src/nextjs/handlers/user.ts, src/nextjs/utils/constants.ts, src/nextjs/utils/getUser.ts, src/nextjs/utils/withAuthRequired.ts, src/shared/utils/jwt.ts
=> feat: return cahced JWT payload.

src/nextjs/handlers/callback.ts, src/nextjs/utils/getUser.ts, src/shared/adapters/NextAdapter.ts, src/shared/adapters/types.ts, src/shared/utils/cookies.ts
Adding adapter interface and NextJS adapter for cookies functions. #25
=> Add adapter to use in cookies functions

CHANGELOG.md, src/shared/utils/jwt.ts
=> fix: Unknown encoding: base64url

CHANGELOG.md, src/nextjs/utils/getUser.ts, src/shared/utils/constants.ts
fix: update cookie lifetime default from 8h to 7 days.
=> fix: update cookie lifetime.

CHANGELOG.md, src/shared/adapters/NextAdapter.ts, src/shared/adapters/types.ts, src/shared/utils/cookies.ts
=> fix: update cookie values on request object.

CHANGELOG.md, examples/nextjs/pages/github-provider-token.tsx, examples/nextjs/pages/index.tsx, examples/nextjs/pages/middleware-protected/_middleware.ts, examples/nextjs/pages/middleware-protected/index.tsx, src/nextjs/README.md, src/nextjs/handlers/callback.ts, src/nextjs/handlers/logout.ts, src/nextjs/index.ts, src/nextjs/utils/withMiddlewareAuthRequired.ts, src/shared/adapters/NextMiddlewareAdapter.ts
- [#44](https://github.com/supabase-community/supabase-auth-helpers/pull/43): feat: Add `withMiddlewareAuthRequired` Nextjs Middleware util to protect directories.
- [#43](https://github.com/supabase-community/supabase-auth-helpers/pull/43): feat: store `provider_token` in cookie.
=> feat: 1.3.0 release

src/react/components/UserProvider.tsx
=> fix: token refresh loop

CHANGELOG.md, package-lock.json, src/nextjs/middleware/withMiddlewareAuth.ts, src/package-lock.json, src/react/index.tsx, src/react/types.ts, src/shared/utils/jwt.ts
- [#95](https://github.com/supabase-community/supabase-auth-helpers/pull/95): fix: change middleware to use pure fetch. Fixes #90
- [#95](https://github.com/supabase-community/supabase-auth-helpers/pull/95): fix: `atob` is not defined. Fixes #93
=> fix: middleware use pure fetch

examples/nextjs/pages/middleware-protected/_middleware.ts, packages/nextjs/README.md, packages/nextjs/src/middleware/withMiddlewareAuth.ts
Add new feature requested in #103.
Continued from #104
=> Add permission guard to midddleware

packages/sveltekit/README.md
Indents were all over the place. This will make them more consistent. Prettier was used to format.
=> More consistent code formatting in README

packages/sveltekit/README.md
Update docs to reflect the examples.
=> fix doc: update sveltekit http method names

examples/sveltekit-email-password/src/routes/index.ts
Made URL dynamic to make the example more general and to prevent bugs if the example is copied into a different project.
Builds of #189.
=> Dynamic url sveltekit email password example

.changeset/sixty-kangaroos-drop.md, packages/nextjs/src/index.ts, packages/nextjs/src/middleware/withMiddlewareAuth.ts, packages/react/src/index.tsx, packages/shared/src/supabase-browser.ts, packages/shared/src/supabase-server.ts, packages/shared/src/types.ts
=> chore: improve types.

examples/sveltekit-email-password/src/routes/(app)/logging-in/+page@.svelte, examples/sveltekit-magic-link/src/routes/logging-in/+page.svelte, examples/sveltekit/src/routes/+page.svelte, packages/sveltekit/src/client.ts
Fixes #226 
Bug fix
> Client Side DB queries don't work when refreshing the page
They work!
=> fix: Client Side DB queries don't work when refreshing the page (#226)

examples/nextjs/package.json, examples/nextjs/pages/index.tsx, pnpm-lock.yaml
* remove deprecated supabase-ui from next example
=> chore: cleanup supabase/ui from next eg

packages/nextjs/README.md
address docs issues raised in https://old.reddit.com/r/Supabase/comments/y8mx4j/flutterdart_authentication_state_and_user_not/it3vaz6/
=> fix: nextjs docs

packages/sveltekit/README.md
=> add Protecting multiple routes section

examples/sveltekit-email-password/package.json, examples/sveltekit-email-password/src/routes/(app)/+page.server.ts, examples/sveltekit-email-password/src/routes/(app)/signup/+page.server.ts, examples/sveltekit-magic-link/package.json, examples/sveltekit-magic-link/src/routes/+page.server.ts, examples/sveltekit/package.json, packages/nextjs/src/constants.ts, pnpm-lock.yaml
Example updates to fix #405 
Version locked to pre 1.0.0 of SvelteKit
Version opened to 1.0.0 SvelteKit
=> Update example code to sveltekit 1.0

packages/sveltekit/src/serverStorageAdapter.ts
Remove an assumed typo
no impact
no impact
=> unreachable code after return statement

examples/sveltekit-email-password/src/routes/+layout.ts, examples/sveltekit-magic-link/src/routes/+layout.ts, examples/sveltekit/src/routes/+layout.ts, packages/sveltekit/src/supabaseLoadClient.ts
closes https://github.com/supabase/auth-helpers/issues/470
=> deprecate onAuthStateChange property

.changeset/pre.json
Bug fix, feature, docs update, ...
=> Change next branch to pre-release mode

.changeset/config.json
Bug fix, feature, docs update, ...
=> Change base branch to next

package.json, patches/@changesets__assemble-release-plan@5.2.3.patch, pnpm-lock.yaml
=> Patch for changeset release

.changeset/pink-clouds-shout.md, .changeset/violet-lies-train.md, packages/shared/package.json, packages/shared/src/utils/cookies.ts, pnpm-lock.yaml
Bug fix
Buffer is failing on Vercel Edge Runtime and Cloudflare workers
Buffer should not fail on Vercel Edge Runtime and Cloudflare workers
=> Add jose for cross platform base64url support

.changeset/lazy-cows-shake.md, .changeset/plenty-seas-build.md, packages/shared/package.json, packages/shared/src/utils/cookies.ts, pnpm-lock.yaml
Adding jose support to PKCE setup
=> chore: add jose to .next branch

packages/sveltekit/README.md
=> Remove filterSerializedResponseHeaders comment

examples/nextjs-pages/package.json, examples/sveltekit/src/routes/(app)/+layout.svelte, pnpm-lock.yaml
=> Update example projects

.changeset/dirty-books-begin.md, packages/ssr/src/createBrowserClient.ts, packages/ssr/src/createServerClient.ts
Bug fix, feature, docs update, ...
=> Remove max-age option from cookieOptions

.changeset/real-clocks-develop.md, packages/nextjs/src/middlewareClient.ts
=> Remove the appending of a cookie to the response

examples/nextjs-pages/pages/index.tsx
Chore
Using relative path
Using module name
Resolve: #660 
Using module name instead of relative path for the clarity and concistency
=> chore: update import on nextjs pages index

examples/sveltekit/package.json, packages/sveltekit/package.json, pnpm-lock.yaml
Upgrade Svelte to resolve [this dependabot issue](https://github.com/supabase/auth-helpers/security/dependabot/69)
=> feat: bump sveltekit to v2.4

.changeset/rich-deers-stare.md, .changeset/shy-falcons-fold.md
* Changes made to cookie chunking in ssr package: #726 
* Changes made in server-side storage adapters: #722
=> chore: add missing changesets

README.md
README update
No mention of `ssr` in the README
Added a small paragraph about `ssr` in the read me and link to docs.
Closes #748
=> fix: ssr added to readme.md

.changeset/happy-seahorses-attend.md
Changes made to allow create browser client to allow for one option: https://github.com/supabase/auth-helpers/pull/756
Changes made to allow create browser client to not fail when accessing cookie properties: https://github.com/supabase/auth-helpers/pull/752
=> feat: release v0.2.0

.github/workflows/ci.yml, .github/workflows/docs.yml, .github/workflows/release.yml
* bump the pnpm version in the ci workflows
=> ci: bump pnpm version

.changeset/rotten-papayas-melt.md, packages/nextjs/package.json, packages/react/package.json, packages/remix/package.json, packages/shared/package.json, packages/ssr/package.json, packages/ssr/tsup.config.bundled_i6zwd190p1m.mjs, packages/sveltekit/package.json, pnpm-lock.yaml
* bump supabase-js version across all packages to v2.42.0
=> fix: bump supabase-js

.changeset/five-dancers-nail.md, examples/sveltekit/package.json, packages/shared/package.json, packages/sveltekit/package.json, pnpm-lock.yaml
* includes dependency version upgrades for issues highlighted by dependabot
=> fix: dependabot issues

package.json, pnpm-lock.yaml
Previously nothing worked on my machine because of `tsup` issues.
=> tools: update turborepo

.github/workflows/ci.yml
=> ci: add build job
